<?xml version="1.0" encoding="utf-8"?>
<Database Name="AdventureWorks2008" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSSQLSERVER41;Initial Catalog=AdventureWorks2008;Integrated Security=True" SettingsObjectName="Lab9.Properties.Settings" SettingsPropertyName="AdventureWorks2008ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.lab9" Member="lab9s">
    <Type Name="lab9">
      <Column Name="Name" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="DeparmentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessEntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="lab9_SalesPerson" Member="SalesPersons" ThisKey="BusinessEntityID" OtherKey="BusinessEntityID" Type="SalesPerson" />
    </Type>
  </Table>
  <Table Name="Sales.SalesPerson" Member="SalesPersons">
    <Type Name="SalesPerson">
      <Column Name="BusinessEntityID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalesQuota" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Bonus" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CommissionPct" Type="System.Decimal" DbType="SmallMoney NOT NULL" CanBeNull="false" />
      <Column Name="SalesYTD" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SalesLastYear" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="lab9_SalesPerson" Member="lab9" ThisKey="BusinessEntityID" OtherKey="BusinessEntityID" Type="lab9" IsForeignKey="true" />
    </Type>
  </Table>
</Database>